export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER = "USER_REGISTER";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const CREATE_BOOK = "CREATE_BOOK";

export const GET_BOOK_LIST = "GET_BOOK_LIST";
export const GET_BOOK_LIST_SUCCESS = "GET_BOOK_LIST_SUCCESS";

export const GET_BOOK_DETAIL = "GET_BOOK_DETAIL";
export const GET_BOOK_DETAIL_SUCCESS = "GET_BOOK_DETAIL_SUCCESS";

export const UPDATE_BOOK_DETAIL = "UPDATE_BOOK_DETAIL";
export const DELETE_BOOK = "DELETE_BOOK";